<?php
/**
 * @var $block \Oggetto\AdvancedSearch\Block\Advanced\Form
 */
?>

<?php
$_htmlId = $block->getHtmlId() ? $block->getHtmlId() : '_' . uniqid();
$_colspan = $block->isAddAfter() ? 2 : 1;
?>

<div id="grid<?= /* @escapeNotVerified */ $_htmlId ?>">
    <div class="formContainer">
        <form action="<?php echo $block->getSearchPostUrl() ?>" method="get">
            <div class="admin__control-table-wrapper">
                <table class="admin__control-table" id="search-form">
                    <thead>
                    <tr>
                        <?php foreach ($block->getColumns() as $columnName => $column): ?>
                            <th><?= /* @escapeNotVerified */ __($column['label']) ?></th>
                        <?php endforeach;?>
                        <th class="col-actions" colspan="<?= /* @escapeNotVerified */ $_colspan ?>"><?= /* @escapeNotVerified */ __('Action') ?></th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <td colspan="3">
                            <button type="submit" class="btn btn btn-primary search-submit"><?php echo __('Search') ?></button>
                        </td>
                        <td colspan="<?= count($block->getColumns())+$_colspan ?>" class="col-actions-add">
                            <button id="addToEndBtn<?= /* @escapeNotVerified */ $_htmlId ?>" class="btn btn-outline-dark btn-add" title="<?= /* @escapeNotVerified */ __('Add') ?>" type="button">
                                <span><?= /* @escapeNotVerified */ $block->getAddButtonLabel() ?></span>
                            </button>
                        </td>
                    </tr>
                    </tfoot>
                    <tbody id="addRow<?= /* @escapeNotVerified */ $_htmlId ?>"></tbody>
                </table>
            </div>
        </form>
    </div>
</div>


<script>
    require([
        'mage/template',
        'prototype'
    ], function (mageTemplate) {
        // create row creator
        window.arrayRow<?= /* @escapeNotVerified */ $_htmlId ?> = {

            // define row prototypeJS template
            template: mageTemplate(
                '<tr id="<%- _id %>">'
                <?php foreach ($block->getColumns() as $columnName => $column): ?>
                + '<td>'
                + '<?= /* @escapeNotVerified */ $block->renderCellTemplate($columnName) ?>'
                + '<\/td>'
                <?php endforeach; ?>

                <?php if ($block->isAddAfter()): ?>
                + '<td><button class="action-add" type="button" id="addAfterBtn<%- _id %>"><span><?= /* @escapeNotVerified */ __('Add after') ?><\/span><\/button><\/td>'
                <?php endif; ?>

                + '<td class="col-actions"><button onclick="arrayRow<?= /* @escapeNotVerified */ $_htmlId ?>.del(\'<%- _id %>\')" class="btn btn-outline-dark" type="button"><span>&times;<\/span><\/button><\/td>'
                +'<\/tr>'
            ),

            add: function(rowData, insertAfterId) {
                // generate default template data
                var templateValues;

                // Prepare template values
                if (rowData) {
                    templateValues = rowData;
                } else {
                    var d = new Date();
                    templateValues = {
                    <?php foreach ($block->getColumns() as $columnName => $column): ?>
                    <?= /* @escapeNotVerified */ $columnName ?>: '',
                        'option_extra_attrs': {},
                    <?php endforeach; ?>
                    _id: '_' + d.getTime() + '_' + d.getMilliseconds()
                };
                }

                // Insert new row after specified row or at the bottom
                if (insertAfterId) {
                    Element.insert($(insertAfterId), {after: this.template(templateValues)});
                } else {
                    Element.insert($('addRow<?= /* @escapeNotVerified */ $_htmlId ?>'), {bottom: this.template(templateValues)});
                }

                // Fill controls with data
                if (rowData) {
                    var rowInputElementNames = Object.keys(rowData.column_values);
                    for (var i = 0; i < rowInputElementNames.length; i++) {
                        if ($(rowInputElementNames[i])) {
                            $(rowInputElementNames[i]).setValue(rowData.column_values[rowInputElementNames[i]]);
                        }
                    }
                }

                // Add event for {addAfterBtn} button
                <?php if ($block->isAddAfter()): ?>
                Event.observe('addAfterBtn' + templateValues._id, 'click', this.add.bind(this, false, templateValues._id));
                <?php endif; ?>
            },

            del: function(rowId) {
                $(rowId).remove();
            }
        }

        // bind add action to "Add" button in last row
        Event.observe('addToEndBtn<?= /* @escapeNotVerified */ $_htmlId ?>', 'click', arrayRow<?= /* @escapeNotVerified */ $_htmlId ?>.add.bind(arrayRow<?= /* @escapeNotVerified */ $_htmlId ?>, false, false));

        // add existing rows
        <?php
        foreach ($block->getArrayRows() as $_rowId => $_row) {
            /* @escapeNotVerified */ echo "arrayRow{$_htmlId}.add(" . $_row->toJson() . ");\n";
        }
        ?>
    });
</script>
